### PR TITLE
add vertical separator '--'

### PR DESCRIPTION
**Pull request by servusoft**
see: https://github.com/msoedov/hacker-slides/issues/28
now it works like https://revealjs.com/#/2

### CODE REVIEW

**Comment by msoedov** [comment]
I will pull and review this changes today. Thank you for your contribution! :)

**Comment by msoedov** [comment]
@servusoft Could you please also update the initial slide with the new `--` example?

**Comment by servusoft** [comment]
Ok, I look.

**Comment by servusoft** [comment]
is done.

**Comment by msoedov** [comment]
Great work thank you!

**Comment by servusoft** [comment]
you are welcome!

**Pull request merged**
